### PR TITLE
refactor: handle current, lastest version and add GH variables

### PR DESCRIPTION
**Pull request by jozefrebjak**
This pull request introduces three functions: `check_docker_env()`, `get_installed_version()` and `get_latest_version()`. 

### Function 1 -` check_docker_env()`
This function checks if the application is running inside a Docker container by searching for the `.dockerenv` file in the root directory. If the file exists, then it prints "Running inside a Docker container" otherwise it prints "Not running inside a Docker container".

### Function 2 - `get_installed_version()`
This function retrieves the installed version of CodeIgniter4 framework from the `composer.lock` file. It does so by using the `jq` command to filter the relevant package information and extracting the version number. If the `composer.lock` file is not found, the function prints an error message and exits with a status code of 1.

### Function 3 - `get_latest_version()`
This function retrieves the latest version of CodeIgniter4 framework available for download from the official website. It does so by making a HTTP GET request to the website and searching for a specific pattern in the response string. The function then extracts the version number from this pattern and prints it. If the latest version number cannot be retrieved, the function prints an error message and exits with a status code of 1.

These functions can be used in various ways to obtain information about the environment and version of CodeIgniter4 framework being used.

### The following variables have been introduced:

Variable 1 - `GH_USER_EMAIL`
This variable is initialized to an empty string and is used to store the email address of the user's GitHub account.

Variable 2 - `GH_USER_NAME`
This variable is initialized to an empty string and is used to store the username of the user's GitHub account.

In addition, the getopts command has been used to parse command line arguments passed to the script. The following options are supported:

Option 1 - `-e`
Takes an argument indicating the email address of the user's GitHub account and stores it in the GH_USER_EMAIL variable.

Option 2 - `-n`
Takes an argument indicating the username of the user's GitHub account and stores it in the GH_USER_NAME variable.

If an invalid option is provided, the script prints an error message and exits with a status code of 1.

### Current and Target version

If Statement 1

```sh
# Check if there is a current version and set it to installed version if found
if [[ -z "$CURRENT_VERSION" ]]; then  # checks if the variable CURRENT_VERSIONL is not empty
  CURRENT_VERSION=$INSTALLED_VERSION   # sets the value of CURRENT_VERSION to INSTALLED_VERSION
fi
```

This 'if' statement checks if the CURRENT_VERSION variable is empty and sets it to INSTALLED_VERSION if found. This allows the user to optionally specify a CURRENT_VERSION, or use the installed version if not provided.

If Statement 2

```sh
if [[ -z "$TARGET_VERSION" ]]; then  # checks if the variable TARGET_VERSIONL is not empty
  TARGET_VERSION=$LATEST_VERSION   # sets the value of TARGET_VERSION to LATEST_VERSION
fi
```

This 'if' statement checks if the TARGET_VERSION variable is empty and sets it to LATEST_VERSION if found. This allows the user to optionally specify a TARGET_VERSION, or use the latest version if not provided.

Overall, these changes help the user provide necessary information for future updates to CodeIgniter4 while allowing them to be flexible in their input.

### CODE REVIEW

**Comment by jozefrebjak** [comment]
The new function `install_dependencies()` checks if the required commands `jq`, `cut` and `grep` are installed on the system or not. If any of these commands are missing, it installs them based on the Linux distribution using package managers like `yum`, `dnf`, `zypper`, or `apk`. If the system is running on Windows (MINGW), it installs the dependencies using Chocolatey package manager. This function ensures that all necessary dependencies are installed before executing the main code, preventing any errors due to missing dependencies.

**Comment by MGatner** [comment]
@jozefrebjak this is awesome work, but moves this script into a whole new realm of complexity. I hope that you've been using your work for yourself, and appreciate that you want to share it. If you feel there is a benefit to including it here I would ask that you include this as a separate initiation point (a new script). I would also be happy to have links in the README out to a repo that you maintain to plug your work "for more advanced use cases".

**Comment by jozefrebjak** [comment]
@MGatner thanks for your comment. Yes I'm using it in my projects. I just need to be able to run patches in docker container, so I'll create new PR where I just add this functionality. It's only about specify GitHub username & email, because docker container doesn't know about local config.

**Comment by MGatner** [comment]
That sounds great! And please don't think I am unappreciative of all the work you put into this - I definitely think you should publish it somewhere as it could be very relevant to others with your same use-case.

**Pull request closed without merging**
